wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 437
EPOCH:
  desc: null
  value: 106
HIDDEN_SIZE_LANG:
  desc: null
  value: 282
HIDDEN_SIZE_LSTM:
  desc: null
  value: 984
HIDDEN_SIZE_SENT:
  desc: null
  value: 182
LAMBDA:
  desc: null
  value: 0.6104489148339131
LSTM_DROPOUT:
  desc: null
  value: 0.2836934018781671
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
