wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 287
EPOCH:
  desc: null
  value: 212
HIDDEN_SIZE_LANG:
  desc: null
  value: 551
HIDDEN_SIZE_LSTM:
  desc: null
  value: 803
HIDDEN_SIZE_SENT:
  desc: null
  value: 358
LAMBDA:
  desc: null
  value: 0.6926476255964805
LSTM_DROPOUT:
  desc: null
  value: 0.24981572528670154
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
