wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 503
EPOCH:
  desc: null
  value: 190
HIDDEN_SIZE_LANG:
  desc: null
  value: 416
HIDDEN_SIZE_LSTM:
  desc: null
  value: 137
HIDDEN_SIZE_SENT:
  desc: null
  value: 585
LAMBDA:
  desc: null
  value: 0.8331725465637841
LSTM_DROPOUT:
  desc: null
  value: 0.2206279738463729
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
