wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 487
EPOCH:
  desc: null
  value: 282
HIDDEN_SIZE_LANG:
  desc: null
  value: 923
HIDDEN_SIZE_LSTM:
  desc: null
  value: 730
HIDDEN_SIZE_SENT:
  desc: null
  value: 603
LAMBDA:
  desc: null
  value: 0.6902012190655986
LSTM_DROPOUT:
  desc: null
  value: 0.39727018394835234
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
