wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 383
EPOCH:
  desc: null
  value: 217
HIDDEN_SIZE_LANG:
  desc: null
  value: 714
HIDDEN_SIZE_LSTM:
  desc: null
  value: 722
HIDDEN_SIZE_SENT:
  desc: null
  value: 724
LAMBDA:
  desc: null
  value: 0.7286065859921628
LSTM_DROPOUT:
  desc: null
  value: 0.13025991456744673
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
