wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 305
EPOCH:
  desc: null
  value: 162
HIDDEN_SIZE_LANG:
  desc: null
  value: 117
HIDDEN_SIZE_LSTM:
  desc: null
  value: 691
HIDDEN_SIZE_SENT:
  desc: null
  value: 243
LAMBDA:
  desc: null
  value: 0.7283595768828431
LSTM_DROPOUT:
  desc: null
  value: 0.2686860164108331
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
