wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 464
EPOCH:
  desc: null
  value: 132
HIDDEN_SIZE_LANG:
  desc: null
  value: 399
HIDDEN_SIZE_LSTM:
  desc: null
  value: 486
HIDDEN_SIZE_SENT:
  desc: null
  value: 456
LAMBDA:
  desc: null
  value: 0.8744381823694195
LSTM_DROPOUT:
  desc: null
  value: 0.14936882889242248
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
