wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 448
EPOCH:
  desc: null
  value: 182
HIDDEN_SIZE_LANG:
  desc: null
  value: 438
HIDDEN_SIZE_LSTM:
  desc: null
  value: 268
HIDDEN_SIZE_SENT:
  desc: null
  value: 456
LAMBDA:
  desc: null
  value: 0.8629193576012668
LSTM_DROPOUT:
  desc: null
  value: 0.31668158805731383
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
