wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 327
EPOCH:
  desc: null
  value: 102
HIDDEN_SIZE_LANG:
  desc: null
  value: 208
HIDDEN_SIZE_LSTM:
  desc: null
  value: 174
HIDDEN_SIZE_SENT:
  desc: null
  value: 350
LAMBDA:
  desc: null
  value: 0.33609710453124875
LSTM_DROPOUT:
  desc: null
  value: 0.28308121953966553
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
