wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 397
EPOCH:
  desc: null
  value: 128
HIDDEN_SIZE_LANG:
  desc: null
  value: 393
HIDDEN_SIZE_LSTM:
  desc: null
  value: 776
HIDDEN_SIZE_SENT:
  desc: null
  value: 836
LAMBDA:
  desc: null
  value: 0.5545352178634423
LSTM_DROPOUT:
  desc: null
  value: 0.22023017409890844
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
