wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 359
EPOCH:
  desc: null
  value: 202
HIDDEN_SIZE_LANG:
  desc: null
  value: 873
HIDDEN_SIZE_LSTM:
  desc: null
  value: 190
HIDDEN_SIZE_SENT:
  desc: null
  value: 125
LAMBDA:
  desc: null
  value: 0.45232375226879606
LSTM_DROPOUT:
  desc: null
  value: 0.3121368419469003
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
