wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 384
EPOCH:
  desc: null
  value: 120
HIDDEN_SIZE_LANG:
  desc: null
  value: 349
HIDDEN_SIZE_LSTM:
  desc: null
  value: 135
HIDDEN_SIZE_SENT:
  desc: null
  value: 457
LAMBDA:
  desc: null
  value: 0.6244974262722403
LSTM_DROPOUT:
  desc: null
  value: 0.25058636654475924
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
