wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 433
EPOCH:
  desc: null
  value: 205
HIDDEN_SIZE_LANG:
  desc: null
  value: 762
HIDDEN_SIZE_LSTM:
  desc: null
  value: 224
HIDDEN_SIZE_SENT:
  desc: null
  value: 1011
LAMBDA:
  desc: null
  value: 0.7750770625788479
LSTM_DROPOUT:
  desc: null
  value: 0.2180181416576735
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
