wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 489
EPOCH:
  desc: null
  value: 150
HIDDEN_SIZE_LANG:
  desc: null
  value: 259
HIDDEN_SIZE_LSTM:
  desc: null
  value: 391
HIDDEN_SIZE_SENT:
  desc: null
  value: 452
LAMBDA:
  desc: null
  value: 0.7596308386265589
LSTM_DROPOUT:
  desc: null
  value: 0.25617910956581413
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
