wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 399
EPOCH:
  desc: null
  value: 315
HIDDEN_SIZE_LANG:
  desc: null
  value: 287
HIDDEN_SIZE_LSTM:
  desc: null
  value: 313
HIDDEN_SIZE_SENT:
  desc: null
  value: 412
LAMBDA:
  desc: null
  value: 0.7256419779343586
LSTM_DROPOUT:
  desc: null
  value: 0.3524625002885351
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
