wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 366
EPOCH:
  desc: null
  value: 199
HIDDEN_SIZE_LANG:
  desc: null
  value: 1010
HIDDEN_SIZE_LSTM:
  desc: null
  value: 771
HIDDEN_SIZE_SENT:
  desc: null
  value: 377
LAMBDA:
  desc: null
  value: 0.5581642807689736
LSTM_DROPOUT:
  desc: null
  value: 0.3949198671746653
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
