wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 275
EPOCH:
  desc: null
  value: 162
HIDDEN_SIZE_LANG:
  desc: null
  value: 218
HIDDEN_SIZE_LSTM:
  desc: null
  value: 480
HIDDEN_SIZE_SENT:
  desc: null
  value: 183
LAMBDA:
  desc: null
  value: 0.26303733972978116
LSTM_DROPOUT:
  desc: null
  value: 0.3806268586695055
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
