wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 337
EPOCH:
  desc: null
  value: 105
HIDDEN_SIZE_LANG:
  desc: null
  value: 1020
HIDDEN_SIZE_LSTM:
  desc: null
  value: 625
HIDDEN_SIZE_SENT:
  desc: null
  value: 385
LAMBDA:
  desc: null
  value: 0.21429234731871755
LSTM_DROPOUT:
  desc: null
  value: 0.21446765112510313
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
