wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 485
EPOCH:
  desc: null
  value: 120
HIDDEN_SIZE_LANG:
  desc: null
  value: 395
HIDDEN_SIZE_LSTM:
  desc: null
  value: 330
HIDDEN_SIZE_SENT:
  desc: null
  value: 313
LAMBDA:
  desc: null
  value: 0.49877795466540187
LSTM_DROPOUT:
  desc: null
  value: 0.28703684015006625
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
