name: LISA_env
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - python
  - pytorch
  - scikit-learn
  - nltk
  - faiss-gpu
  - tensorflow
  - spacy
  - pyyaml
  - pip:
    - wandb
    - gensim
