wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 502
EPOCH:
  desc: null
  value: 113
HIDDEN_SIZE_LANG:
  desc: null
  value: 605
HIDDEN_SIZE_LSTM:
  desc: null
  value: 608
HIDDEN_SIZE_SENT:
  desc: null
  value: 620
LAMBDA:
  desc: null
  value: 0.4988111165083958
LSTM_DROPOUT:
  desc: null
  value: 0.19604969446730947
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
