wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 457
EPOCH:
  desc: null
  value: 286
HIDDEN_SIZE_LANG:
  desc: null
  value: 446
HIDDEN_SIZE_LSTM:
  desc: null
  value: 156
HIDDEN_SIZE_SENT:
  desc: null
  value: 437
LAMBDA:
  desc: null
  value: 0.10061768712002986
LSTM_DROPOUT:
  desc: null
  value: 0.23008740188235519
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
