wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 310
EPOCH:
  desc: null
  value: 237
HIDDEN_SIZE_LANG:
  desc: null
  value: 261
HIDDEN_SIZE_LSTM:
  desc: null
  value: 106
HIDDEN_SIZE_SENT:
  desc: null
  value: 838
LAMBDA:
  desc: null
  value: 0.7444959463300094
LSTM_DROPOUT:
  desc: null
  value: 0.17884916720477728
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
