wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 455
EPOCH:
  desc: null
  value: 230
HIDDEN_SIZE_LANG:
  desc: null
  value: 891
HIDDEN_SIZE_LSTM:
  desc: null
  value: 866
HIDDEN_SIZE_SENT:
  desc: null
  value: 196
LAMBDA:
  desc: null
  value: 0.46045027322994747
LSTM_DROPOUT:
  desc: null
  value: 0.19018527464435825
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
