wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 380
EPOCH:
  desc: null
  value: 252
HIDDEN_SIZE_LANG:
  desc: null
  value: 510
HIDDEN_SIZE_LSTM:
  desc: null
  value: 593
HIDDEN_SIZE_SENT:
  desc: null
  value: 624
LAMBDA:
  desc: null
  value: 0.3031274172016195
LSTM_DROPOUT:
  desc: null
  value: 0.286674996207385
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
