wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 472
EPOCH:
  desc: null
  value: 167
HIDDEN_SIZE_LANG:
  desc: null
  value: 213
HIDDEN_SIZE_LSTM:
  desc: null
  value: 185
HIDDEN_SIZE_SENT:
  desc: null
  value: 342
LAMBDA:
  desc: null
  value: 0.8379652713495259
LSTM_DROPOUT:
  desc: null
  value: 0.20468512633220762
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
