wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 465
EPOCH:
  desc: null
  value: 231
HIDDEN_SIZE_LANG:
  desc: null
  value: 281
HIDDEN_SIZE_LSTM:
  desc: null
  value: 382
HIDDEN_SIZE_SENT:
  desc: null
  value: 228
LAMBDA:
  desc: null
  value: 0.3219301133265258
LSTM_DROPOUT:
  desc: null
  value: 0.19827742105386287
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
