wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 507
EPOCH:
  desc: null
  value: 158
HIDDEN_SIZE_LANG:
  desc: null
  value: 368
HIDDEN_SIZE_LSTM:
  desc: null
  value: 178
HIDDEN_SIZE_SENT:
  desc: null
  value: 401
LAMBDA:
  desc: null
  value: 0.8949442136661491
LSTM_DROPOUT:
  desc: null
  value: 0.3312050336435821
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
