wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 491
EPOCH:
  desc: null
  value: 186
HIDDEN_SIZE_LANG:
  desc: null
  value: 721
HIDDEN_SIZE_LSTM:
  desc: null
  value: 174
HIDDEN_SIZE_SENT:
  desc: null
  value: 604
LAMBDA:
  desc: null
  value: 0.6548790357578282
LSTM_DROPOUT:
  desc: null
  value: 0.2681414235338321
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
