wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 330
EPOCH:
  desc: null
  value: 205
HIDDEN_SIZE_LANG:
  desc: null
  value: 161
HIDDEN_SIZE_LSTM:
  desc: null
  value: 875
HIDDEN_SIZE_SENT:
  desc: null
  value: 523
LAMBDA:
  desc: null
  value: 0.4009866358272294
LSTM_DROPOUT:
  desc: null
  value: 0.19050136321579836
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
