wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 265
EPOCH:
  desc: null
  value: 216
HIDDEN_SIZE_LANG:
  desc: null
  value: 402
HIDDEN_SIZE_LSTM:
  desc: null
  value: 328
HIDDEN_SIZE_SENT:
  desc: null
  value: 684
LAMBDA:
  desc: null
  value: 0.8069471745498064
LSTM_DROPOUT:
  desc: null
  value: 0.1832855700186621
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
