wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 265
EPOCH:
  desc: null
  value: 118
HIDDEN_SIZE_LANG:
  desc: null
  value: 278
HIDDEN_SIZE_LSTM:
  desc: null
  value: 174
HIDDEN_SIZE_SENT:
  desc: null
  value: 258
LAMBDA:
  desc: null
  value: 0.8761450981712778
LSTM_DROPOUT:
  desc: null
  value: 0.2874344442486334
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
