wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 500
epochs:
  desc: null
  value: 200
log_interval:
  desc: null
  value: 10
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 500
