wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 347
EPOCH:
  desc: null
  value: 391
HIDDEN_SIZE_LANG:
  desc: null
  value: 196
HIDDEN_SIZE_LSTM:
  desc: null
  value: 255
HIDDEN_SIZE_SENT:
  desc: null
  value: 167
LAMBDA:
  desc: null
  value: 0.16683431337835736
LSTM_DROPOUT:
  desc: null
  value: 0.3658204690741177
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
