wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 284
EPOCH:
  desc: null
  value: 374
HIDDEN_SIZE_LANG:
  desc: null
  value: 423
HIDDEN_SIZE_LSTM:
  desc: null
  value: 147
HIDDEN_SIZE_SENT:
  desc: null
  value: 119
LAMBDA:
  desc: null
  value: 0.2633490149258287
LSTM_DROPOUT:
  desc: null
  value: 0.24725346521530975
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
