wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 448
EPOCH:
  desc: null
  value: 251
HIDDEN_SIZE_LANG:
  desc: null
  value: 230
HIDDEN_SIZE_LSTM:
  desc: null
  value: 350
HIDDEN_SIZE_SENT:
  desc: null
  value: 985
LAMBDA:
  desc: null
  value: 0.36211431894689994
LSTM_DROPOUT:
  desc: null
  value: 0.16827292940837207
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
