wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 322
EPOCH:
  desc: null
  value: 250
HIDDEN_SIZE_LANG:
  desc: null
  value: 238
HIDDEN_SIZE_LSTM:
  desc: null
  value: 195
HIDDEN_SIZE_SENT:
  desc: null
  value: 651
LAMBDA:
  desc: null
  value: 0.19577654073888545
LSTM_DROPOUT:
  desc: null
  value: 0.17045345310992632
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
