wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 319
EPOCH:
  desc: null
  value: 208
HIDDEN_SIZE_LANG:
  desc: null
  value: 697
HIDDEN_SIZE_LSTM:
  desc: null
  value: 160
HIDDEN_SIZE_SENT:
  desc: null
  value: 404
LAMBDA:
  desc: null
  value: 0.8659895706691629
LSTM_DROPOUT:
  desc: null
  value: 0.13435865993883553
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
