wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 443
EPOCH:
  desc: null
  value: 157
HIDDEN_SIZE_LANG:
  desc: null
  value: 248
HIDDEN_SIZE_LSTM:
  desc: null
  value: 161
HIDDEN_SIZE_SENT:
  desc: null
  value: 452
LAMBDA:
  desc: null
  value: 0.710267879084539
LSTM_DROPOUT:
  desc: null
  value: 0.2536419782255656
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
