wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 291
EPOCH:
  desc: null
  value: 211
HIDDEN_SIZE_LANG:
  desc: null
  value: 819
HIDDEN_SIZE_LSTM:
  desc: null
  value: 792
HIDDEN_SIZE_SENT:
  desc: null
  value: 724
LAMBDA:
  desc: null
  value: 0.6459443630298999
LSTM_DROPOUT:
  desc: null
  value: 0.27897383398264014
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
