wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 413
EPOCH:
  desc: null
  value: 271
HIDDEN_SIZE_LANG:
  desc: null
  value: 610
HIDDEN_SIZE_LSTM:
  desc: null
  value: 136
HIDDEN_SIZE_SENT:
  desc: null
  value: 283
LAMBDA:
  desc: null
  value: 0.8284723546183981
LSTM_DROPOUT:
  desc: null
  value: 0.275068377648557
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
