wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 433
EPOCH:
  desc: null
  value: 103
HIDDEN_SIZE_LANG:
  desc: null
  value: 158
HIDDEN_SIZE_LSTM:
  desc: null
  value: 163
HIDDEN_SIZE_SENT:
  desc: null
  value: 684
LAMBDA:
  desc: null
  value: 0.7871916802080221
LSTM_DROPOUT:
  desc: null
  value: 0.2564027357385077
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
