wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 311
EPOCH:
  desc: null
  value: 272
HIDDEN_SIZE_LANG:
  desc: null
  value: 583
HIDDEN_SIZE_LSTM:
  desc: null
  value: 127
HIDDEN_SIZE_SENT:
  desc: null
  value: 924
LAMBDA:
  desc: null
  value: 0.5206395718586148
LSTM_DROPOUT:
  desc: null
  value: 0.3097941567701086
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
