wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 411
EPOCH:
  desc: null
  value: 169
HIDDEN_SIZE_LANG:
  desc: null
  value: 499
HIDDEN_SIZE_LSTM:
  desc: null
  value: 441
HIDDEN_SIZE_SENT:
  desc: null
  value: 511
LAMBDA:
  desc: null
  value: 0.8918639991347113
LSTM_DROPOUT:
  desc: null
  value: 0.2721836898531143
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
