wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 400
EPOCH:
  desc: null
  value: 147
HIDDEN_SIZE_LANG:
  desc: null
  value: 347
HIDDEN_SIZE_LSTM:
  desc: null
  value: 985
HIDDEN_SIZE_SENT:
  desc: null
  value: 135
LAMBDA:
  desc: null
  value: 0.6827377949185763
LSTM_DROPOUT:
  desc: null
  value: 0.2107887263907622
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
