wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 276
EPOCH:
  desc: null
  value: 110
HIDDEN_SIZE_LANG:
  desc: null
  value: 189
HIDDEN_SIZE_LSTM:
  desc: null
  value: 386
HIDDEN_SIZE_SENT:
  desc: null
  value: 145
LAMBDA:
  desc: null
  value: 0.2150570887916687
LSTM_DROPOUT:
  desc: null
  value: 0.3867472822096749
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
