wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 489
EPOCH:
  desc: null
  value: 158
HIDDEN_SIZE_LANG:
  desc: null
  value: 263
HIDDEN_SIZE_LSTM:
  desc: null
  value: 219
HIDDEN_SIZE_SENT:
  desc: null
  value: 660
LAMBDA:
  desc: null
  value: 0.8895133366947329
LSTM_DROPOUT:
  desc: null
  value: 0.2474047787421295
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
