wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 280
EPOCH:
  desc: null
  value: 300
HIDDEN_SIZE_LANG:
  desc: null
  value: 412
HIDDEN_SIZE_LSTM:
  desc: null
  value: 831
HIDDEN_SIZE_SENT:
  desc: null
  value: 298
LAMBDA:
  desc: null
  value: 0.6364635069479421
LSTM_DROPOUT:
  desc: null
  value: 0.33813096190047964
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
