wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 364
EPOCH:
  desc: null
  value: 247
HIDDEN_SIZE_LANG:
  desc: null
  value: 845
HIDDEN_SIZE_LSTM:
  desc: null
  value: 766
HIDDEN_SIZE_SENT:
  desc: null
  value: 607
LAMBDA:
  desc: null
  value: 0.6318183257328581
LSTM_DROPOUT:
  desc: null
  value: 0.24737377172885291
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
