wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 420
EPOCH:
  desc: null
  value: 241
HIDDEN_SIZE_LANG:
  desc: null
  value: 373
HIDDEN_SIZE_LSTM:
  desc: null
  value: 719
HIDDEN_SIZE_SENT:
  desc: null
  value: 229
LAMBDA:
  desc: null
  value: 0.7809779728481298
LSTM_DROPOUT:
  desc: null
  value: 0.35198443406738344
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
