wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 295
EPOCH:
  desc: null
  value: 228
HIDDEN_SIZE_LANG:
  desc: null
  value: 323
HIDDEN_SIZE_LSTM:
  desc: null
  value: 800
HIDDEN_SIZE_SENT:
  desc: null
  value: 251
LAMBDA:
  desc: null
  value: 0.8008041630233899
LSTM_DROPOUT:
  desc: null
  value: 0.27562570351973614
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
