wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 373
EPOCH:
  desc: null
  value: 250
HIDDEN_SIZE_LANG:
  desc: null
  value: 478
HIDDEN_SIZE_LSTM:
  desc: null
  value: 247
HIDDEN_SIZE_SENT:
  desc: null
  value: 416
LAMBDA:
  desc: null
  value: 0.5098083478761243
LSTM_DROPOUT:
  desc: null
  value: 0.38095063980558597
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
