wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 306
EPOCH:
  desc: null
  value: 126
HIDDEN_SIZE_LANG:
  desc: null
  value: 189
HIDDEN_SIZE_LSTM:
  desc: null
  value: 1017
HIDDEN_SIZE_SENT:
  desc: null
  value: 411
LAMBDA:
  desc: null
  value: 0.7933677572408032
LSTM_DROPOUT:
  desc: null
  value: 0.36137029652002794
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
