wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 502
EPOCH:
  desc: null
  value: 174
HIDDEN_SIZE_LANG:
  desc: null
  value: 451
HIDDEN_SIZE_LSTM:
  desc: null
  value: 255
HIDDEN_SIZE_SENT:
  desc: null
  value: 166
LAMBDA:
  desc: null
  value: 0.7247464175641921
LSTM_DROPOUT:
  desc: null
  value: 0.25808567430143914
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
