wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 470
EPOCH:
  desc: null
  value: 233
HIDDEN_SIZE_LANG:
  desc: null
  value: 226
HIDDEN_SIZE_LSTM:
  desc: null
  value: 499
HIDDEN_SIZE_SENT:
  desc: null
  value: 497
LAMBDA:
  desc: null
  value: 0.736414529032881
LSTM_DROPOUT:
  desc: null
  value: 0.18092616230367703
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
