wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 294
EPOCH:
  desc: null
  value: 212
HIDDEN_SIZE_LANG:
  desc: null
  value: 649
HIDDEN_SIZE_LSTM:
  desc: null
  value: 141
HIDDEN_SIZE_SENT:
  desc: null
  value: 999
LAMBDA:
  desc: null
  value: 0.5231220357432613
LSTM_DROPOUT:
  desc: null
  value: 0.1953259455383366
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
