wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 410
EPOCH:
  desc: null
  value: 219
HIDDEN_SIZE_LANG:
  desc: null
  value: 143
HIDDEN_SIZE_LSTM:
  desc: null
  value: 626
HIDDEN_SIZE_SENT:
  desc: null
  value: 688
LAMBDA:
  desc: null
  value: 0.6865888707243931
LSTM_DROPOUT:
  desc: null
  value: 0.3648373564645163
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
