wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 446
EPOCH:
  desc: null
  value: 316
HIDDEN_SIZE_LANG:
  desc: null
  value: 488
HIDDEN_SIZE_LSTM:
  desc: null
  value: 359
HIDDEN_SIZE_SENT:
  desc: null
  value: 419
LAMBDA:
  desc: null
  value: 0.5095561240720217
LSTM_DROPOUT:
  desc: null
  value: 0.33664853210093026
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
