wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 407
EPOCH:
  desc: null
  value: 229
HIDDEN_SIZE_LANG:
  desc: null
  value: 347
HIDDEN_SIZE_LSTM:
  desc: null
  value: 172
HIDDEN_SIZE_SENT:
  desc: null
  value: 569
LAMBDA:
  desc: null
  value: 0.6051843052815176
LSTM_DROPOUT:
  desc: null
  value: 0.20421848401563653
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
