wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 472
EPOCH:
  desc: null
  value: 141
HIDDEN_SIZE_LANG:
  desc: null
  value: 794
HIDDEN_SIZE_LSTM:
  desc: null
  value: 548
HIDDEN_SIZE_SENT:
  desc: null
  value: 951
LAMBDA:
  desc: null
  value: 0.277874022936199
LSTM_DROPOUT:
  desc: null
  value: 0.2449349685085355
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
