wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 372
EPOCH:
  desc: null
  value: 203
HIDDEN_SIZE_LANG:
  desc: null
  value: 692
HIDDEN_SIZE_LSTM:
  desc: null
  value: 341
HIDDEN_SIZE_SENT:
  desc: null
  value: 178
LAMBDA:
  desc: null
  value: 0.7489100425576606
LSTM_DROPOUT:
  desc: null
  value: 0.17723411196584976
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
