wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 476
EPOCH:
  desc: null
  value: 106
HIDDEN_SIZE_LANG:
  desc: null
  value: 332
HIDDEN_SIZE_LSTM:
  desc: null
  value: 402
HIDDEN_SIZE_SENT:
  desc: null
  value: 494
LAMBDA:
  desc: null
  value: 0.8870109547132254
LSTM_DROPOUT:
  desc: null
  value: 0.29120132734581916
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
