wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 500
EPOCH:
  desc: null
  value: 256
HIDDEN_SIZE_LANG:
  desc: null
  value: 830
HIDDEN_SIZE_LSTM:
  desc: null
  value: 363
HIDDEN_SIZE_SENT:
  desc: null
  value: 636
LAMBDA:
  desc: null
  value: 0.6533119283750649
LSTM_DROPOUT:
  desc: null
  value: 0.39600944043777486
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
