wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 404
EPOCH:
  desc: null
  value: 346
HIDDEN_SIZE_LANG:
  desc: null
  value: 406
HIDDEN_SIZE_LSTM:
  desc: null
  value: 377
HIDDEN_SIZE_SENT:
  desc: null
  value: 506
LAMBDA:
  desc: null
  value: 0.3964190657352089
LSTM_DROPOUT:
  desc: null
  value: 0.3054693237653797
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
