wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 386
EPOCH:
  desc: null
  value: 209
HIDDEN_SIZE_LANG:
  desc: null
  value: 411
HIDDEN_SIZE_LSTM:
  desc: null
  value: 435
HIDDEN_SIZE_SENT:
  desc: null
  value: 336
LAMBDA:
  desc: null
  value: 0.11797858475581542
LSTM_DROPOUT:
  desc: null
  value: 0.32050000798922695
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
