wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 268
EPOCH:
  desc: null
  value: 229
HIDDEN_SIZE_LANG:
  desc: null
  value: 140
HIDDEN_SIZE_LSTM:
  desc: null
  value: 686
HIDDEN_SIZE_SENT:
  desc: null
  value: 991
LAMBDA:
  desc: null
  value: 0.7008322458676347
LSTM_DROPOUT:
  desc: null
  value: 0.2214814687836991
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
