wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 412
EPOCH:
  desc: null
  value: 124
HIDDEN_SIZE_LANG:
  desc: null
  value: 101
HIDDEN_SIZE_LSTM:
  desc: null
  value: 460
HIDDEN_SIZE_SENT:
  desc: null
  value: 275
LAMBDA:
  desc: null
  value: 0.11764403575442187
LSTM_DROPOUT:
  desc: null
  value: 0.3190884324261532
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
