wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 454
EPOCH:
  desc: null
  value: 195
HIDDEN_SIZE_LANG:
  desc: null
  value: 220
HIDDEN_SIZE_LSTM:
  desc: null
  value: 213
HIDDEN_SIZE_SENT:
  desc: null
  value: 505
LAMBDA:
  desc: null
  value: 0.8550603761720269
LSTM_DROPOUT:
  desc: null
  value: 0.22848342862078314
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
