wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 377
EPOCH:
  desc: null
  value: 167
HIDDEN_SIZE_LANG:
  desc: null
  value: 290
HIDDEN_SIZE_LSTM:
  desc: null
  value: 141
HIDDEN_SIZE_SENT:
  desc: null
  value: 155
LAMBDA:
  desc: null
  value: 0.6933989845952043
LSTM_DROPOUT:
  desc: null
  value: 0.332933250642514
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
