wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 472
EPOCH:
  desc: null
  value: 199
HIDDEN_SIZE_LANG:
  desc: null
  value: 712
HIDDEN_SIZE_LSTM:
  desc: null
  value: 290
HIDDEN_SIZE_SENT:
  desc: null
  value: 485
LAMBDA:
  desc: null
  value: 0.7036976487788122
LSTM_DROPOUT:
  desc: null
  value: 0.3944377832438464
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
