wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 317
EPOCH:
  desc: null
  value: 261
HIDDEN_SIZE_LANG:
  desc: null
  value: 690
HIDDEN_SIZE_LSTM:
  desc: null
  value: 123
HIDDEN_SIZE_SENT:
  desc: null
  value: 516
LAMBDA:
  desc: null
  value: 0.4354896904401794
LSTM_DROPOUT:
  desc: null
  value: 0.20150500843017066
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
