wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 381
EPOCH:
  desc: null
  value: 164
HIDDEN_SIZE_LANG:
  desc: null
  value: 660
HIDDEN_SIZE_LSTM:
  desc: null
  value: 307
HIDDEN_SIZE_SENT:
  desc: null
  value: 472
LAMBDA:
  desc: null
  value: 0.2092643506191485
LSTM_DROPOUT:
  desc: null
  value: 0.3933105145563611
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
