wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 431
EPOCH:
  desc: null
  value: 253
HIDDEN_SIZE_LANG:
  desc: null
  value: 143
HIDDEN_SIZE_LSTM:
  desc: null
  value: 209
HIDDEN_SIZE_SENT:
  desc: null
  value: 197
LAMBDA:
  desc: null
  value: 0.7197037754770411
LSTM_DROPOUT:
  desc: null
  value: 0.1901800724953155
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
