wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 478
EPOCH:
  desc: null
  value: 129
HIDDEN_SIZE_LANG:
  desc: null
  value: 296
HIDDEN_SIZE_LSTM:
  desc: null
  value: 302
HIDDEN_SIZE_SENT:
  desc: null
  value: 295
LAMBDA:
  desc: null
  value: 0.7883945416154747
LSTM_DROPOUT:
  desc: null
  value: 0.2644954841915966
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
