wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 419
EPOCH:
  desc: null
  value: 222
HIDDEN_SIZE_LANG:
  desc: null
  value: 624
HIDDEN_SIZE_LSTM:
  desc: null
  value: 247
HIDDEN_SIZE_SENT:
  desc: null
  value: 996
LAMBDA:
  desc: null
  value: 0.14477248521033534
LSTM_DROPOUT:
  desc: null
  value: 0.11272979742951302
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
