wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 498
EPOCH:
  desc: null
  value: 245
HIDDEN_SIZE_LANG:
  desc: null
  value: 340
HIDDEN_SIZE_LSTM:
  desc: null
  value: 278
HIDDEN_SIZE_SENT:
  desc: null
  value: 173
LAMBDA:
  desc: null
  value: 0.8660189558174717
LSTM_DROPOUT:
  desc: null
  value: 0.2508730927863588
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
