wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 323
EPOCH:
  desc: null
  value: 150
HIDDEN_SIZE_LANG:
  desc: null
  value: 148
HIDDEN_SIZE_LSTM:
  desc: null
  value: 169
HIDDEN_SIZE_SENT:
  desc: null
  value: 267
LAMBDA:
  desc: null
  value: 0.3366851965135226
LSTM_DROPOUT:
  desc: null
  value: 0.3952357761045304
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
