wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 284
EPOCH:
  desc: null
  value: 123
HIDDEN_SIZE_LANG:
  desc: null
  value: 195
HIDDEN_SIZE_LSTM:
  desc: null
  value: 148
HIDDEN_SIZE_SENT:
  desc: null
  value: 806
LAMBDA:
  desc: null
  value: 0.12704321518726838
LSTM_DROPOUT:
  desc: null
  value: 0.27316031986098455
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
