wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 364
EPOCH:
  desc: null
  value: 151
HIDDEN_SIZE_LANG:
  desc: null
  value: 245
HIDDEN_SIZE_LSTM:
  desc: null
  value: 334
HIDDEN_SIZE_SENT:
  desc: null
  value: 128
LAMBDA:
  desc: null
  value: 0.10375877178086679
LSTM_DROPOUT:
  desc: null
  value: 0.17496287323721288
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
