wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 423
EPOCH:
  desc: null
  value: 216
HIDDEN_SIZE_LANG:
  desc: null
  value: 257
HIDDEN_SIZE_LSTM:
  desc: null
  value: 146
HIDDEN_SIZE_SENT:
  desc: null
  value: 431
LAMBDA:
  desc: null
  value: 0.7070353139166045
LSTM_DROPOUT:
  desc: null
  value: 0.28306963438837973
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
