wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 480
EPOCH:
  desc: null
  value: 112
HIDDEN_SIZE_LANG:
  desc: null
  value: 360
HIDDEN_SIZE_LSTM:
  desc: null
  value: 290
HIDDEN_SIZE_SENT:
  desc: null
  value: 469
LAMBDA:
  desc: null
  value: 0.8887417102503269
LSTM_DROPOUT:
  desc: null
  value: 0.38860254878125466
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
