wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 510
EPOCH:
  desc: null
  value: 245
HIDDEN_SIZE_LANG:
  desc: null
  value: 478
HIDDEN_SIZE_LSTM:
  desc: null
  value: 120
HIDDEN_SIZE_SENT:
  desc: null
  value: 789
LAMBDA:
  desc: null
  value: 0.6044450484427639
LSTM_DROPOUT:
  desc: null
  value: 0.23426961109233213
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
