wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 473
EPOCH:
  desc: null
  value: 262
HIDDEN_SIZE_LANG:
  desc: null
  value: 720
HIDDEN_SIZE_LSTM:
  desc: null
  value: 308
HIDDEN_SIZE_SENT:
  desc: null
  value: 709
LAMBDA:
  desc: null
  value: 0.5947901815538805
LSTM_DROPOUT:
  desc: null
  value: 0.368792678677338
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
