wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 431
EPOCH:
  desc: null
  value: 116
HIDDEN_SIZE_LANG:
  desc: null
  value: 219
HIDDEN_SIZE_LSTM:
  desc: null
  value: 388
HIDDEN_SIZE_SENT:
  desc: null
  value: 166
LAMBDA:
  desc: null
  value: 0.14655724407461435
LSTM_DROPOUT:
  desc: null
  value: 0.13484584083729825
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
