wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 444
EPOCH:
  desc: null
  value: 104
HIDDEN_SIZE_LANG:
  desc: null
  value: 253
HIDDEN_SIZE_LSTM:
  desc: null
  value: 266
HIDDEN_SIZE_SENT:
  desc: null
  value: 198
LAMBDA:
  desc: null
  value: 0.6914191609191969
LSTM_DROPOUT:
  desc: null
  value: 0.36232903013096895
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
