wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 413
EPOCH:
  desc: null
  value: 276
HIDDEN_SIZE_LANG:
  desc: null
  value: 493
HIDDEN_SIZE_LSTM:
  desc: null
  value: 555
HIDDEN_SIZE_SENT:
  desc: null
  value: 605
LAMBDA:
  desc: null
  value: 0.3819040051500927
LSTM_DROPOUT:
  desc: null
  value: 0.12863744700644758
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
