wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 492
EPOCH:
  desc: null
  value: 284
HIDDEN_SIZE_LANG:
  desc: null
  value: 486
HIDDEN_SIZE_LSTM:
  desc: null
  value: 221
HIDDEN_SIZE_SENT:
  desc: null
  value: 870
LAMBDA:
  desc: null
  value: 0.3423520786747841
LSTM_DROPOUT:
  desc: null
  value: 0.320127527743728
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
