wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 458
EPOCH:
  desc: null
  value: 147
HIDDEN_SIZE_LANG:
  desc: null
  value: 878
HIDDEN_SIZE_LSTM:
  desc: null
  value: 896
HIDDEN_SIZE_SENT:
  desc: null
  value: 443
LAMBDA:
  desc: null
  value: 0.388071669151532
LSTM_DROPOUT:
  desc: null
  value: 0.3906482411199296
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
