wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 372
EPOCH:
  desc: null
  value: 294
HIDDEN_SIZE_LANG:
  desc: null
  value: 1017
HIDDEN_SIZE_LSTM:
  desc: null
  value: 990
HIDDEN_SIZE_SENT:
  desc: null
  value: 175
LAMBDA:
  desc: null
  value: 0.18438773072359435
LSTM_DROPOUT:
  desc: null
  value: 0.2868244338128876
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
