wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 281
EPOCH:
  desc: null
  value: 122
HIDDEN_SIZE_LANG:
  desc: null
  value: 287
HIDDEN_SIZE_LSTM:
  desc: null
  value: 144
HIDDEN_SIZE_SENT:
  desc: null
  value: 960
LAMBDA:
  desc: null
  value: 0.399152007186822
LSTM_DROPOUT:
  desc: null
  value: 0.35935528056529287
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
