wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 291
EPOCH:
  desc: null
  value: 105
HIDDEN_SIZE_LANG:
  desc: null
  value: 548
HIDDEN_SIZE_LSTM:
  desc: null
  value: 487
HIDDEN_SIZE_SENT:
  desc: null
  value: 804
LAMBDA:
  desc: null
  value: 0.614923259410484
LSTM_DROPOUT:
  desc: null
  value: 0.21785977882328955
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
