wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 350
EPOCH:
  desc: null
  value: 130
HIDDEN_SIZE_LANG:
  desc: null
  value: 158
HIDDEN_SIZE_LSTM:
  desc: null
  value: 534
HIDDEN_SIZE_SENT:
  desc: null
  value: 950
LAMBDA:
  desc: null
  value: 0.28463419126573963
LSTM_DROPOUT:
  desc: null
  value: 0.2055845706348905
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
