wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 267
EPOCH:
  desc: null
  value: 156
HIDDEN_SIZE_LANG:
  desc: null
  value: 155
HIDDEN_SIZE_LSTM:
  desc: null
  value: 506
HIDDEN_SIZE_SENT:
  desc: null
  value: 344
LAMBDA:
  desc: null
  value: 0.255455226770961
LSTM_DROPOUT:
  desc: null
  value: 0.17907282888915238
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
