wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 457
EPOCH:
  desc: null
  value: 275
HIDDEN_SIZE_LANG:
  desc: null
  value: 256
HIDDEN_SIZE_LSTM:
  desc: null
  value: 955
HIDDEN_SIZE_SENT:
  desc: null
  value: 136
LAMBDA:
  desc: null
  value: 0.3305063519475445
LSTM_DROPOUT:
  desc: null
  value: 0.34903428196591113
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
