wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 285
EPOCH:
  desc: null
  value: 138
HIDDEN_SIZE_LANG:
  desc: null
  value: 145
HIDDEN_SIZE_LSTM:
  desc: null
  value: 363
HIDDEN_SIZE_SENT:
  desc: null
  value: 495
LAMBDA:
  desc: null
  value: 0.8779776989507594
LSTM_DROPOUT:
  desc: null
  value: 0.26423637004666434
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
