wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 350
EPOCH:
  desc: null
  value: 102
HIDDEN_SIZE_LANG:
  desc: null
  value: 194
HIDDEN_SIZE_LSTM:
  desc: null
  value: 775
HIDDEN_SIZE_SENT:
  desc: null
  value: 578
LAMBDA:
  desc: null
  value: 0.7988717224629241
LSTM_DROPOUT:
  desc: null
  value: 0.13766760562877273
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
