wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 379
EPOCH:
  desc: null
  value: 115
HIDDEN_SIZE_LANG:
  desc: null
  value: 202
HIDDEN_SIZE_LSTM:
  desc: null
  value: 226
HIDDEN_SIZE_SENT:
  desc: null
  value: 203
LAMBDA:
  desc: null
  value: 0.5597053259153196
LSTM_DROPOUT:
  desc: null
  value: 0.16555939723188687
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
