wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 442
EPOCH:
  desc: null
  value: 167
HIDDEN_SIZE_LANG:
  desc: null
  value: 275
HIDDEN_SIZE_LSTM:
  desc: null
  value: 828
HIDDEN_SIZE_SENT:
  desc: null
  value: 944
LAMBDA:
  desc: null
  value: 0.2170575554175568
LSTM_DROPOUT:
  desc: null
  value: 0.11927302457990357
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
