wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 469
EPOCH:
  desc: null
  value: 172
HIDDEN_SIZE_LANG:
  desc: null
  value: 306
HIDDEN_SIZE_LSTM:
  desc: null
  value: 363
HIDDEN_SIZE_SENT:
  desc: null
  value: 443
LAMBDA:
  desc: null
  value: 0.8865904139130115
LSTM_DROPOUT:
  desc: null
  value: 0.20741076370665892
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
