wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 367
EPOCH:
  desc: null
  value: 197
HIDDEN_SIZE_LANG:
  desc: null
  value: 682
HIDDEN_SIZE_LSTM:
  desc: null
  value: 358
HIDDEN_SIZE_SENT:
  desc: null
  value: 145
LAMBDA:
  desc: null
  value: 0.34779997420311604
LSTM_DROPOUT:
  desc: null
  value: 0.2699787501313058
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
