wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 389
EPOCH:
  desc: null
  value: 278
HIDDEN_SIZE_LANG:
  desc: null
  value: 928
HIDDEN_SIZE_LSTM:
  desc: null
  value: 603
HIDDEN_SIZE_SENT:
  desc: null
  value: 775
LAMBDA:
  desc: null
  value: 0.11218489240837136
LSTM_DROPOUT:
  desc: null
  value: 0.13557370860165316
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
