wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 451
EPOCH:
  desc: null
  value: 217
HIDDEN_SIZE_LANG:
  desc: null
  value: 737
HIDDEN_SIZE_LSTM:
  desc: null
  value: 707
HIDDEN_SIZE_SENT:
  desc: null
  value: 314
LAMBDA:
  desc: null
  value: 0.4293585944508911
LSTM_DROPOUT:
  desc: null
  value: 0.39474964890889597
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
