wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 333
EPOCH:
  desc: null
  value: 100
HIDDEN_SIZE_LANG:
  desc: null
  value: 389
HIDDEN_SIZE_LSTM:
  desc: null
  value: 364
HIDDEN_SIZE_SENT:
  desc: null
  value: 114
LAMBDA:
  desc: null
  value: 0.46261570592143775
LSTM_DROPOUT:
  desc: null
  value: 0.3068448881821194
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
