wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 412
EPOCH:
  desc: null
  value: 104
HIDDEN_SIZE_LANG:
  desc: null
  value: 206
HIDDEN_SIZE_LSTM:
  desc: null
  value: 123
HIDDEN_SIZE_SENT:
  desc: null
  value: 437
LAMBDA:
  desc: null
  value: 0.5575819142674667
LSTM_DROPOUT:
  desc: null
  value: 0.2460660840303377
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
