wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 428
EPOCH:
  desc: null
  value: 149
HIDDEN_SIZE_LANG:
  desc: null
  value: 301
HIDDEN_SIZE_LSTM:
  desc: null
  value: 426
HIDDEN_SIZE_SENT:
  desc: null
  value: 420
LAMBDA:
  desc: null
  value: 0.8193791487771094
LSTM_DROPOUT:
  desc: null
  value: 0.2366293776623519
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
