wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 506
EPOCH:
  desc: null
  value: 162
HIDDEN_SIZE_LANG:
  desc: null
  value: 376
HIDDEN_SIZE_LSTM:
  desc: null
  value: 178
HIDDEN_SIZE_SENT:
  desc: null
  value: 668
LAMBDA:
  desc: null
  value: 0.7408578269899962
LSTM_DROPOUT:
  desc: null
  value: 0.13148909219765018
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
