wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 326
EPOCH:
  desc: null
  value: 123
HIDDEN_SIZE_LANG:
  desc: null
  value: 174
HIDDEN_SIZE_LSTM:
  desc: null
  value: 664
HIDDEN_SIZE_SENT:
  desc: null
  value: 269
LAMBDA:
  desc: null
  value: 0.1528025468721908
LSTM_DROPOUT:
  desc: null
  value: 0.32515132681548187
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
