wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 392
EPOCH:
  desc: null
  value: 108
HIDDEN_SIZE_LANG:
  desc: null
  value: 998
HIDDEN_SIZE_LSTM:
  desc: null
  value: 113
HIDDEN_SIZE_SENT:
  desc: null
  value: 392
LAMBDA:
  desc: null
  value: 0.25751757812347204
LSTM_DROPOUT:
  desc: null
  value: 0.12048949906844801
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
