wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 303
EPOCH:
  desc: null
  value: 285
HIDDEN_SIZE_LANG:
  desc: null
  value: 197
HIDDEN_SIZE_LSTM:
  desc: null
  value: 102
HIDDEN_SIZE_SENT:
  desc: null
  value: 466
LAMBDA:
  desc: null
  value: 0.4367406978080053
LSTM_DROPOUT:
  desc: null
  value: 0.18407419264878383
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
