wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 508
EPOCH:
  desc: null
  value: 154
HIDDEN_SIZE_LANG:
  desc: null
  value: 522
HIDDEN_SIZE_LSTM:
  desc: null
  value: 282
HIDDEN_SIZE_SENT:
  desc: null
  value: 430
LAMBDA:
  desc: null
  value: 0.42833942639017275
LSTM_DROPOUT:
  desc: null
  value: 0.3001511762536992
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
