wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 357
EPOCH:
  desc: null
  value: 188
HIDDEN_SIZE_LANG:
  desc: null
  value: 177
HIDDEN_SIZE_LSTM:
  desc: null
  value: 118
HIDDEN_SIZE_SENT:
  desc: null
  value: 578
LAMBDA:
  desc: null
  value: 0.6892348790262781
LSTM_DROPOUT:
  desc: null
  value: 0.21818303301261077
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
