wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 363
EPOCH:
  desc: null
  value: 218
HIDDEN_SIZE_LANG:
  desc: null
  value: 692
HIDDEN_SIZE_LSTM:
  desc: null
  value: 855
HIDDEN_SIZE_SENT:
  desc: null
  value: 573
LAMBDA:
  desc: null
  value: 0.4729122824609572
LSTM_DROPOUT:
  desc: null
  value: 0.12786848804747486
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
