wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 485
EPOCH:
  desc: null
  value: 233
HIDDEN_SIZE_LANG:
  desc: null
  value: 276
HIDDEN_SIZE_LSTM:
  desc: null
  value: 396
HIDDEN_SIZE_SENT:
  desc: null
  value: 391
LAMBDA:
  desc: null
  value: 0.44168065660537426
LSTM_DROPOUT:
  desc: null
  value: 0.2913015203396011
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
