wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 261
EPOCH:
  desc: null
  value: 125
HIDDEN_SIZE_LANG:
  desc: null
  value: 997
HIDDEN_SIZE_LSTM:
  desc: null
  value: 114
HIDDEN_SIZE_SENT:
  desc: null
  value: 181
LAMBDA:
  desc: null
  value: 0.632815166441924
LSTM_DROPOUT:
  desc: null
  value: 0.23542750198430293
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
