wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 314
EPOCH:
  desc: null
  value: 297
HIDDEN_SIZE_LANG:
  desc: null
  value: 271
HIDDEN_SIZE_LSTM:
  desc: null
  value: 263
HIDDEN_SIZE_SENT:
  desc: null
  value: 318
LAMBDA:
  desc: null
  value: 0.7665139655137364
LSTM_DROPOUT:
  desc: null
  value: 0.14996970738249407
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
