wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 400
EPOCH:
  desc: null
  value: 115
HIDDEN_SIZE_LANG:
  desc: null
  value: 616
HIDDEN_SIZE_LSTM:
  desc: null
  value: 809
HIDDEN_SIZE_SENT:
  desc: null
  value: 331
LAMBDA:
  desc: null
  value: 0.5449820170971308
LSTM_DROPOUT:
  desc: null
  value: 0.15171893878859333
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
