wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 400
EPOCH:
  desc: null
  value: 185
HIDDEN_SIZE_LANG:
  desc: null
  value: 311
HIDDEN_SIZE_LSTM:
  desc: null
  value: 1012
HIDDEN_SIZE_SENT:
  desc: null
  value: 672
LAMBDA:
  desc: null
  value: 0.4674543159207515
LSTM_DROPOUT:
  desc: null
  value: 0.21105974712314096
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
