wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 373
EPOCH:
  desc: null
  value: 140
HIDDEN_SIZE_LANG:
  desc: null
  value: 580
HIDDEN_SIZE_LSTM:
  desc: null
  value: 790
HIDDEN_SIZE_SENT:
  desc: null
  value: 384
LAMBDA:
  desc: null
  value: 0.7784009896087712
LSTM_DROPOUT:
  desc: null
  value: 0.17970410458608194
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
