wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 368
EPOCH:
  desc: null
  value: 144
HIDDEN_SIZE_LANG:
  desc: null
  value: 952
HIDDEN_SIZE_LSTM:
  desc: null
  value: 579
HIDDEN_SIZE_SENT:
  desc: null
  value: 276
LAMBDA:
  desc: null
  value: 0.2612096413758074
LSTM_DROPOUT:
  desc: null
  value: 0.3360159932247241
_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
